Repository KusionStack/kclvm-py, pull requests merged in 2023-01, with the labels that each got.

#5 feat: add unit tests
  .github/workflows/test.yaml
  Makefile
  README.md
  internal/scripts/test_unit.sh
  kclvm/compiler/parser/lark_parser.pickle
  kclvm/tools/printer/printer.py
  setup.py
  test/test_units/test_kclvm/test_api/test_object/test_decorator_obj.py
  test/test_units/test_kclvm/test_compiler/test_astutil/test_ast_filter.py
  test/test_units/test_kclvm/test_compiler/test_extension/test_builtin/test_units_module.py
  test/test_units/test_kclvm/test_rpc_server/test_rpc_server.py
  test/test_units/test_kclvm/test_tools/test_lint/test_checker/test_kcl_checker.py
  test/test_units/test_kclvm/test_tools/test_list_attr/test_kcl_schema.py
  test/test_units/test_kclvm/test_tools/test_printer/test_ast_printer.py
Labels: test

#6 Fix(kclvm-py): fix windows dll path.
  kclvm/program/exec/kclvm_cli.py
Labels: enhancement

#7 fix: config if entry type unsoundness.
  kclvm/kcl/types/checker.py
  kclvm/program/exec/kclvm_cli.py
  setup.py
  test/grammar/types/var_type_annotation/type_fail_10/main.k
  test/grammar/types/var_type_annotation/type_fail_10/stderr.golden.py
  test/grammar/types/var_type_annotation/type_fail_11/main.k
  test/grammar/types/var_type_annotation/type_fail_11/stderr.golden.py
  test/grammar/types/var_type_annotation/type_fail_12/main.k
  test/grammar/types/var_type_annotation/type_fail_12/stderr.golden.py
  test/grammar/types/var_type_annotation/type_fail_13/main.k
  test/grammar/types/var_type_annotation/type_fail_13/stderr.golden.py
  test/grammar/types/var_type_annotation/type_fail_14/main.k
  test/grammar/types/var_type_annotation/type_fail_14/stderr.golden.py
Labels: bug
